const mongoose = require('mongoose');

const ExpenseSchema = new mongoose.Schema({
  title: String,
  amount: Number,
  date: { type: Date, default: Date.now },
  isAutoGenerated: { type: Boolean, default: false },
  deduplicationKey: String, // ΑΥΤΟ ΕΛΕΙΠΕ ΚΑΙ ΓΙ' ΑΥΤΟ ΔΕΝ ΔΟΥΛΕΥΕ Η ΠΡΟΣΤΑΣΙΑ
  shop: { type: mongoose.Schema.Types.ObjectId, ref: 'Shop', required: true }
});

module.exports = mongoose.model('Expense', ExpenseSchema);